# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "The 405 Found "
email: "hireforheart@gmail.com"
description: "The 405 Found Project highlights how diverse talent is all around us."
baseurl: "/the405found.github.io"
url: "https://the405found.github.io/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Hire for Heart"
organizerAlternateName: "Hire for Heart"
organizerDescription: "Hire for Heart works to fight bias, create opportunities, and bridge the gap for those underrepresented in technology."
organizerEmail: "hireforheart@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.hireforheart.com"


# Head
metaKeywords: "event, the 405 Found, diversity, equity, inclusion, opportunity, talent, technology, skills, bridge the gap"
twitterAccount: "@the405found"
#/sharing-google-plus.png"
#socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
#socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://forms.gle/5j7HFvsTEPQAcbc86"
c4sponsorsUrl: "/assets/405Found_Sponsorship.pdf"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers + Volunteers"}
 - {permalink: "/team/", text: "About"}
# - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://forms.gle/5j7HFvsTEPQAcbc86", text: "Become a Workshop Presenter or Volunteer"}
rightNavigationButtons:
 - {link: "https://forms.gle/5j7HFvsTEPQAcbc86", text: "Become a Workshop Presenter or Volunteer"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "The 405 Found: <typeout> 2020"
eventDate: "October 22, 2020"
typeoutTextValues: '"", "Talent", "Opportunity", "Potential", "Recruit"'
typeoutFallback: "Talent"
heroButtons:
 - {link: "https://forms.gle/5j7HFvsTEPQAcbc86", text: "Become a Workshop Presenter or Volunteer"}
 - {link: "http://www.eventbrite.com", text: "Register"}

# About Block
aboutTitle: "About The 405 Found"
aboutBlock:
 - {title: "Panel", image: "panel.jpg", text: "Panelists with varying backgrounds and experiences in technical and non-SWE (non-software-engineering) positions will speak about how they identified and created opportunities to either start or enhance their own tech careers." }
 - {title: "Workshops", image: "workshop.jpg", text: "Professionals can choose from a roster of workshops to attend that are relevant to varying career stages because of the different needs." }
 - {title: "1-on-1 Guidance", image: "one-on-one.jpg", text: "Volunteers are ready to help in a more customized way, whether you're looking for someone to provide feedback on your resume, conduct a mock interview, or wanted to chat one-on-one for career guidance (e.g. career transition)." }
 - {title: "Exhibit Hall", image: "one-on-one.jpg", text: "Volunteers are ready to help in a more customized way, whether you're looking for someone to provide feedback on your resume, conduct a mock interview, or wanted to chat one-on-one for career guidance (e.g. career transition)." }


 # Statistic Block
#statisticBlockImage: "statistic.jpg"
#statisticBlock:
# - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
# - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
# - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
# - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
#latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 7
rockstarSpeakersTitle: "Panelist Speakers"
rockstarSpeakersButtonText: "See everyone contributing time and talent to make this a success"

# Location Block
#locationBlockTitle: "Location"
#eventLocationName: "Conference Hall"
#eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
#eventStreetAddress: "22 Teatral'na St"
#eventAddressLocality: "Lviv"
#eventAddressLocalityRegion: "Lvivska"
#eventPostalCode: "79000"
#eventAddressCountry: "Ukraine"
#eventStartTime: "2014-10-25T10:00"
#eventDoorTime: "09:00"
#eventEndTime: "2014-10-25T20:00"
#eventPlaceCoordinates: "49.843237, 24.028751"
#mapCenterCoordinates: "49.842537, 24.025701"
#mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
#venueBlockTitle: "Venue"
#venueBigImage: "venue_0.jpg"
#venueSmallImage1: "venue_1.jpg"
#venueSmallImage2: "venue_2.jpg"
#venueSmallImage3: "venue_3.jpg"
#venueTitle: "Kinopalace Cinema"
#venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
#tweetsFeedImage: "twitter-feed.jpg"
#tweetsFeedTitle: "What's Up?"
#twitterHashTag: "devfest"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
#subscribeImage: "subscribe.jpg"
#subscribeTitle: "Subscribe for updates"
#subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
#subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
#ticketsTitle: "Pricetable"
#ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
#ticketsOffers:
# -
#  name: "Early Bird"
#  price: "350"
#  priceCurrency: "UAH"
#  ticketsNumber: "150"
#  ribbon: "-5%"
#  buyButtonLink: "http://dfua.ticketforevent.com/"
#  buyButtonText: "Buy Now"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-08-25T10:00"
#  validThrough: "2014-09-30T23:59"
# -
#  name: "Last Chance"
#  price: "450"
#  priceCurrency: "UAH"
#  ticketsNumber: "100"
#  ribbon: "-20%"
#  featured: true
#  buyButtonLink: "http://dfua.ticketforevent.com/"
#  buyButtonText: "Buy Now"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-10-01T00:00"
#  validThrough: "2014-10-23T23:59"
#  disabled: true
# -
#  name: "Student"
#  price: "200"
#  priceCurrency: "UAH"
#  ticketsNumber: "50"
#  buyButtonLink: "http://dfua.ticketforevent.com/"
#  buyButtonText: "Buy Now"
#  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-08-20T10:00"
#  validThrough: "2014-10-23T23:59"
#  soldOut: true
#  soldOutText: "Sold Out"

# Footer
#socialLinks:
# - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
# - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
# - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
# - {permalink: "/feed.xml", icon: "rss"}
#footerBlocks:
# -
#  title: "Links"
#  links:
#   - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
#   - {link: "https://developers.google.com", text: "Google Developers"}
# -
#  title: "Contacts"
#  links:
#   - {link: "mailto:lviv@gdg.org.ua", text: "lviv@gdg.org.ua"}
# -
#  title: "FAQ"
#  links:
#   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
#blogTitle: "Latest news"
#blogCommentsEnabled: true
#discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "<a href='https://www.codeforboston.org/'><b>Code for Boston</b></a> is a volunteer Civic Technology meetup. We are part of the Code for America Brigade network, and are made up of developers, designers, data geeks, citizen activists, and many others who use creative technology to solve civic and social problems.
<br><br>
Hire for Heart works to fight bias, create opportunities, and bridge the gap for those underrepresented in technology."

# Logistics Find Way Block
#findWayTitle: "Find your way here"
#findWayDistance: "Distance"
#findWayDriving: "DRIVING"
#findWayWalking: "WALKING"
#findWayBicycling: "BICYCLING"
#findWayTransit: "TRANSIT"
#findWayFindFlight: "Find Flight"
#logisticsMapCenterCoordinates: "49.056728, 3.117289"
#logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
#logisticsMapAutoDirections: false

# Logistics Direction Details Block
#directionDetailsImage: "direction-details.jpg"
#directionDetailsTitle: "Get around Lviv"
#directionDetailsCards:
# - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
# - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
# - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
#directionDetailsWideCards:
# -
#  title: "Questions?"
#  subCards:
#   -
#    title: "Hotels"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Registration"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Attendance Details"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
#hackathonTitle: "Hackathon"
#enableHackathon: true

# Hackathon About Block
#aboutHackathonTitle: "Meet our themes"
#hackathonRows:
# - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
# - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
# - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didnâ€™t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
#judgesImage: "judges.jpg"
#judgesTitle: "Judges"

# Hackathon Prizes Block
#prizesTitle: "Prizes"
#prizes:
# - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
# - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
# - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
#hackathonLocationBlockTitle: "Location"
#hackathonLocationName: "Communa"
#hackathonLocationLink: "http://communa.net.ua/"
#hackathonStreetAddress: "1 Halytska St"
#hackathonAddressLocality: "Lviv"
#hackathonAddressLocalityRegion: "Lvivska"
#hackathonPostalCode: "79000"
#hackathonAddressCountry: "Ukraine"
#hackathonTimeTitle: "Hack through"
#hackathonStartTime: "2014-10-24T10:00"
#hackathonDoorTime: "09:00"
#hackathonEndTime: "2014-10-25T00:00"
#viewOnMap: "View on Google Maps"
#hackathonPlaceCoordinates: "49.840999, 24.031144"
#hackathonMapCenterCoordinates: "49.840696, 24.028754"
#hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
